imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
imports:
- { resource: "@FdrAdminBundle/Resources/config/services.yml" }
framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    translator: ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ FOSUserBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
#        yui_css:
#            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
#        yui_js:
#            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    encryption:  "%mailer_encryption%"
    spool:     { type: memory }
    
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Fdr\UserBundle\Entity\User
    registration:
        form:
            #handler: fdr_user.form.handler.registration
            type: fdr_user_registration

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:sliding.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template
        
ensepar_html2pdf:
    orientation: P
    format: A4
    lang: fr
    unicode: true
    encoding: UTF-8
    margin: [15,20,15,20]

#JMS  Security
#jms_security_extra:
#    secure_all_services: false
#    enable_iddqd_attribute: false
#    expressions: true
#    voters:
#        disable_authenticated: false
#        disable_role:          false
#        disable_acl:           false
#    method_access_control:
#        ':loginAction$': 'isAnonymous()'
#
#    util:
#        secure_random:
#            connection: 
#            table_name: seed_table
#            seed_provider: entitie_manager
