<?php

namespace Komay\bundles\Idea1Bundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DossierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DossierRepository extends EntityRepository
{
}
