<?php

namespace Fdr\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ChauffeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChauffeurRepository extends EntityRepository {
     public function chauffeurs ()
    {
        $qb=$this->createQueryBuilder('c');
        return $qb;//->getQuery()->getResult()
    }
}
