<?php

namespace Fdr\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DepotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepotRepository extends EntityRepository {

    public function getDepots() {

        $qb = $this->createQueryBuilder('d')
                ->where('d.station = :station')
                ->setParameter('station', 'oui')
                ->orderBy('d.station', 'Asc');
        return $qb; //->getQuery()->getResult()
    }

}
