<?php

namespace Fdr\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ParametrageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParametrageRepository extends EntityRepository {
    
}
