<?php

namespace Fdr\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VehiculeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehiculeRepository extends EntityRepository
{
    public function vehicules ()
    {
     
        $qb=$this->createQueryBuilder('v');
        return $qb;//->getQuery()->getResult()
    }
}
