<?php

namespace Fdr\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VilleRepository extends EntityRepository {

    public function villes() {

        $qb = $this->createQueryBuilder('v')
                ->orderBy('v.libelle', 'Asc');
        return $qb; //->getQuery()->getResult()
    }

}
