fdr_user_user:
    resource: "@FdrUserBundle/Resources/config/routing/user.yml"
    prefix:   /user

fdr_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: FdrUserBundle:Default:index }
