services:
#    fdr_user.example:
#        class: Fdr\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    fdr_user.registration.form.type:
        class: Fdr\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: fdr_user_registration }
#    fdr_user.form.handler.registration:
#        class: Fdr\UserBundle\Form\Handler\RegistrationFormHandler
#        arguments: ["@fos_user.registration.form", "@request", "@fos_user.user_manager", "@fos_user.mailer"]
#        scope: request
#        public: false